# Generated by Django 6.0.3 on 2026-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=' ', upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
