# Generated by Django 6.0.3 on 2026-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_image_url_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
