// SectionHeaderCenter.jsx
import styles from '../styles/SectionHeaderCenter.module.css';
import { FaArrowRight } from 'react-icons/fa';


const SectionHeaderCenter = ({ caption, title, subtitle, description }) => {

    const handleScroll = () => {
        // We look for the first service card on the page
        // Use the actual class name generated by CSS modules (or a plain string if not using modules for the card)
        const firstCard = document.querySelector('[class*="card"]'); 
        
        if (firstCard) {
            firstCard.scrollIntoView({ 
                behavior: 'smooth', 
                block: 'start' 
            });
        }
    };

    return (
        <header className={styles['banner-container']}>
            <div className={styles['banner-content']}>
                {/* 1. Caption */}
                {caption && <span className={styles['banner-caption']}>{caption}</span>}
                
                {/* 2. Title */}
                <h1 className={styles['banner-title']}>{title}</h1>
                
                {/* 3. Subtitle */}
                <h2 className={styles['banner-subtitle']}>{subtitle}</h2>
                
                {/* 4. Description */}
                {description && <p className={styles['banner-description']}>{description}</p>}
                
                {/* 5. CTA Button */}
                <button className={styles['banner-cta']} onClick={handleScroll}>Explore Our Services <FaArrowRight/> </button>
            </div>
        </header>
    );
};

export default SectionHeaderCenter;